[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
log = "0.4.27"
env_logger = "0.11.8"
nalgebra = "0.33.2"
rayon = "1.10.0"
rand = "0.9.1"
rand_distr = "0.5.1"
indicatif = { version = "0.17.11", features = ["rayon"] }
